### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by minhd-vu** [minhd-vu/tower-defense-3d#6]
Required Game Mechanics:
- [x] [Enemy Health Bar](https://www.youtube.com/watch?v=BLfNP4Sc_iA&ab_channel=Brackeys)
- [x] Currency Deduction on Weapon Build
- [x] Currency Increase on Enemy Death
- [ ] Camera Controller
- [x] Increase Score on Enemy Death
- [x] Pausing

Optional Game Mechanics:
- [ ] Gameover Screen
- [ ] Scaling Enemies

Submission:
- [ ] Slide Deck Presentation
- [ ] Demo Video
- [x] Technical Report

**Comment by minhd-vu** [comment]
https://user-images.githubusercontent.com/18576915/145604368-ccfb6707-08f0-457f-8230-ac9beb1c768b.mp4

https://user-images.githubusercontent.com/18576915/145604387-f9129cd8-0d23-4c5f-aa3f-595e7cb6f7b0.mp4
